# Generated by Django 4.2.5 on 2023-10-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category_home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_type", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="Category_Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name_select", models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=45)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Shior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title1", models.CharField(max_length=25)),
                ("title2", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/team")),
                ("facebook_link", models.URLField(max_length=255)),
                ("instagram_link", models.URLField(max_length=255)),
                ("telegram_link", models.URLField(max_length=255)),
                ("full_name", models.CharField(max_length=40)),
                ("profession", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/home")),
                ("price", models.FloatField()),
                ("company_name", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=35)),
                ("maydoni", models.FloatField()),
                ("uy_count", models.PositiveIntegerField()),
                ("bathroom_count", models.PositiveIntegerField()),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theapp.category_name",
                    ),
                ),
                (
                    "home_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theapp.category_home",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/category")),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theapp.category_name",
                    ),
                ),
            ],
        ),
    ]
