# Generated by Django 4.2.4 on 2023-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shior',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
