# Generated by Django 4.2.4 on 2023-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_alter_shior_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
