# Generated by Django 4.2.4 on 2023-10-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
