# Generated by Django 4.2.4 on 2023-10-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
