# Generated by Django 4.1.10 on 2023-10-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0006_remove_team_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="name1",
        ),
    ]
