# Generated by Django 4.1.10 on 2023-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0007_rename_name_contact_name1"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
